export const responses = {
  successCreateItem: "Adding new Item was successful",
  successUpdateItem: "Updating Item was successful",
  successDeleteItem: "Deleting Item was successful",
  successGetItem: "Item has been found",
  errorNotFound: "Item not found",
  errorCreateItem: "An error occurred adding new Item",
  errorUpdateItem: "An error occurred updating the Item",
  errorDeleteItem: "An error occurred deleting the Item",
  serverError: "A server error occurred",
  successSignUp: "Sign up was successful",
  successSignIn: "Sign in was successful",
  userIsExist: "User already exist",
  errorSignUp: "Invalid created new user",
  errorSignIn: "Invalid username or password",
  errorField: "Please recheck field!",
  errorUserNotFound: "User not found",
};
